-- =============================================================================
-- Migration 012 — iam_audit_logs
-- Schema: public (auth_db)
-- Service: iam-service
--
-- Business-logic audit log for the IAM service.
-- Records significant user-management actions (role changes, permission updates, etc.).
-- Separate from the HTTP-level audit_logs table already present in the IAM DB.
--
-- id         — UUIDv4, uppercase, generated by the application
-- user_id    — UUID of the user who performed the action
-- created_at — timestamp with timezone (date + time)
-- created_by — username / display name of the actor
-- logs       — plain-text description of the action performed
--              e.g. "User 'test' changed permission for superadmin from 'READ' to 'READ,WRITE'"
-- =============================================================================

CREATE TABLE IF NOT EXISTS audit_logs (
  uuid        VARCHAR(36)   NOT NULL,
  user_id     VARCHAR(36)   NOT NULL,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  created_by  VARCHAR(255)  NOT NULL,
  logs        TEXT          NOT NULL,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (uuid)
);
