-- =============================================================================
-- Migration 013 — email_audit_logs
-- Schema: public (email_db)
-- Service: email-service
--
-- Business-logic audit log for the email service.
-- Records significant actions such as sending, retrying or blacklisting.
--
-- id         — UUIDv4, uppercase, generated by the application
-- user_id    — UUID of the user who performed the action
-- created_at — timestamp with timezone (date + time)
-- created_by — username / display name of the actor
-- logs       — plain-text description of the action performed
--              e.g. "User 'test' blacklisted email provider 'sendgrid'"
-- =============================================================================

CREATE TABLE IF NOT EXISTS audit_logs (
  uuid        VARCHAR(36)   NOT NULL,
  user_id     VARCHAR(36)   NOT NULL,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  created_by  VARCHAR(255)  NOT NULL,
  logs        TEXT          NOT NULL,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (uuid)
);
