-- =============================================================================
-- Migration 014 — programme_audit_logs
-- Schema: programme
-- Service: programme-service
--
-- Business-logic audit log for the programme service.
-- Records significant actions on programmes, rules, rule groups, and beneficiaries.
-- Separate from the domain-level programme_history / programme_rules_history tables.
--
-- id         — UUIDv4, uppercase, generated by the application
-- user_id    — UUID of the user who performed the action
-- created_at — timestamp with timezone (date + time)
-- created_by — username / display name of the actor
-- logs       — plain-text description of the action performed
--              e.g. "User 'test' deleted rule 'Income Check' from programme 'JSLC 2025'"
-- =============================================================================


CREATE TABLE IF NOT EXISTS programme.audit_logs (
  uuid        VARCHAR(36)   NOT NULL,
  user_id     VARCHAR(36)   NOT NULL,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  created_by  VARCHAR(255)  NOT NULL,
  logs        TEXT          NOT NULL,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (uuid)
);
